CC = icc
CFLAGS = -O3 -xW -unroll -ip -mp -Werror #-openmp
INCLUDE = -I/usr/local/include -I/usr/local/include/SuperLU -I/programs/i386/lib/intel/ipp/5.0/ia32/include
FLAGS = -DINTEL_C -DMVTIME #-DOMP
LDFLAGS = $(CFLAGS) -static-libcxa -i-static
LIBDIR = -L/usr/local/lib -L/programs/i386/lib/intel/ipp/5.0/ia32/lib -L/programs/i386/lib/intel/mkl/8.0.1/lib/32
LIBS = -lsuperlu -llapack -lfftw3 -lfftw3f -lippsemerged -lippsmerged -lippcore
